### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by ultimaweapon**
When I tried to build on Linux it is errors with the following messages:

```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 141.17 ms for /home/ultimaweapon/Workspace/zcoin/AsyncEvent/src/AsyncEvent/AsyncEvent.csproj.
  Restore completed in 141.17 ms for /home/ultimaweapon/Workspace/zcoin/AsyncEvent/examples/Thermometer/Thermometer.csproj.
/home/ultimaweapon/Workspace/zcoin/AsyncEvent/src/AsyncEvent/AsyncEvent.csproj : error NU1202: Package dotnet-setversion 2.1.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package dotnet-setversion 2.1.0 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any [/home/ultimaweapon/Workspace/zcoin/AsyncEvent/async-event.sln]
/home/ultimaweapon/Workspace/zcoin/AsyncEvent/src/AsyncEvent/AsyncEvent.csproj : error NU1212: Invalid project-package combination for dotnet-setversion 2.1.0. DotnetToolReference project style can only contain references of the DotnetTool type  [/home/ultimaweapon/Workspace/zcoin/AsyncEvent/async-event.sln]
  Restore failed in 2.72 sec for /home/ultimaweapon/Workspace/zcoin/AsyncEvent/src/AsyncEvent/AsyncEvent.csproj.
  Restore completed in 10.27 sec for /home/ultimaweapon/Workspace/zcoin/AsyncEvent/test/AsyncEvent.Tests/AsyncEvent.Tests.csproj.
  Restore completed in 18.12 sec for /home/ultimaweapon/Workspace/zcoin/AsyncEvent/test/AsyncEvent.Tests/AsyncEvent.Tests.csproj.

Build FAILED.

/home/ultimaweapon/Workspace/zcoin/AsyncEvent/src/AsyncEvent/AsyncEvent.csproj : error NU1202: Package dotnet-setversion 2.1.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package dotnet-setversion 2.1.0 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any [/home/ultimaweapon/Workspace/zcoin/AsyncEvent/async-event.sln]
/home/ultimaweapon/Workspace/zcoin/AsyncEvent/src/AsyncEvent/AsyncEvent.csproj : error NU1212: Invalid project-package combination for dotnet-setversion 2.1.0. DotnetToolReference project style can only contain references of the DotnetTool type  [/home/ultimaweapon/Workspace/zcoin/AsyncEvent/async-event.sln]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:19.26
```

So this PR fixes this error.

### CODE REVIEW

**Comment by TAGC** [comment]
Thanks for the PR.

It's a step in the right direction to remove dotnet-setversion from the csproj file, but it's still needed in order to set the version of the project during CI builds. It's been migrated to a global CLI tool since the last time this project was updated, so `appveyor.yml` will need to be modified to install the tool on the CI file system and then invoke that version of the tool.

dotnet-setversion actually uses itself to maintain its own versioning so [its own appveyor.yml file](https://github.com/TAGC/dotnet-setversion/blob/master/appveyor.yml) can be used for reference.

**Comment by TAGC** [comment]
If you want, I could make the necessary changes when I have time and push to your branch.

**Comment by ultimaweapon** [comment]
Yes please.

**Comment by TAGC** [comment]
Sure, can you grant me permission to push changes to your branch please?

**Comment by ultimaweapon** [comment]
Not sure why there are no `Allow edits from maintainers` checkbox. So I added you to a forked repository directly. Please check.

**Comment by TAGC** [comment]
Crap, accidentally merged that into master.

**Comment by TAGC** [comment]
I'm not sure if you've got the option, but can you rebase this on `TAGC:develop` if possible?

**Comment by ultimaweapon** [comment]
Sorry for the late response. I will do it now and create another PR.

**Pull request merged**
