### PR TITLE
Fixes InvokeAsync on generic handler with no subscribers

### PR DESCRIPTION
**Pull request by ultimaweapon**
Not sure why it did not check on a generic version.

### CODE REVIEW

**Comment by TAGC** [comment]
Thanks, I'm not sure either.

**Review by katdti — COMMENTED** [review]
The if(eventHandler == null) test os not very thread safe.
Would prefer:
var delegates = eventHandler?.GetInvocationList()?Cast...
var tasks = delegates?.Select...
if ((tasks?.Count ?? 0 )== 0) return Task.Completed;

**Comment by ultimaweapon** [comment]
In this context it will be thread-safe due to it is an argument. If will be unsafe only if we access the event object in the class directly.

**Comment by katdti** [comment]
Interesting argument. 
After some reading I must agree with you. 
Even if Microsoft writes extension methods "[behave as and member function](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods)"
**this** is passed as "value"

**Pull request merged**
